"""Complete action catalog for the Wildberries MCP server.

Every tool exposed by the server is described as an Action dataclass.
The server dispatches calls via ``getattr(api, action.api_method)``
with validated params from the corresponding Pydantic model.

Pattern inspired by the Yandex Metrika MCP server.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from pydantic import BaseModel

from .models import (
    # Shared / Reusable
    OrderIdParams,
    OrderIdsParams,
    SupplyIdParams,
    CampaignIdParams,
    TaskIdParams,
    PassThroughParams,
    # Content
    SubjectIdParams,
    SubjectsListParams,
    BrandsParams,
    TagCreateParams,
    TagUpdateParams,
    TagIdParams,
    TagLinkParams,
    CardsListParams,
    CardsUpdateParams,
    # FBS Orders
    FbsOrdersParams,
    FbsStickersParams,
    FbsSupplyCreateParams,
    FbsSuppliesParams,
    FbsSupplyAddOrdersParams,
    FbsPassUpdateParams,
    FbsPassCreateParams,
    PassIdParams,
    # FBS / DBW Order Metadata
    OrderSgtinParams,
    OrderUinParams,
    OrderImeiParams,
    OrderGtinParams,
    OrderExpirationParams,
    OrderCustomsParams,
    # DBS / Pickup Batch Metadata
    OrdersBatchParams,
    # FBW
    FbwAcceptanceOptionsParams,
    FbwSuppliesFilterParams,
    # Advertising
    CampaignIdsParams,
    CampaignRenameParams,
    CampaignBudgetDepositParams,
    AdvertBidsUpdateParams,
    AdvertDateRangeParams,
    AdvertMinBidsParams,
    AdvertCampaignCreateParams,
    AdvertNmsParams,
    AdvertPlacementsUpdateParams,
    AdvertNmsUpdateParams,
    AdvertSearchBidsGetParams,
    AdvertSearchBidsSetParams,
    AdvertMinusPhraseGetParams,
    AdvertMinusPhraseSetParams,
    AdvertSearchStatsParams,
    # Communications
    QuestionsParams,
    QuestionsCountParams,
    QuestionManageParams,
    QuestionIdParams,
    FeedbacksParams,
    FeedbacksCountParams,
    FeedbackAnswerParams,
    FeedbackIdParams,
    FeedbacksArchiveParams,
    NmIdParams,
    FeedbackPinParams,
    ChatSendParams,
    # Tariffs
    TariffDateParams,
    # Analytics
    AnalyticsSalesFunnelParams,
    AnalyticsSalesFunnelHistoryParams,
    AnalyticsSalesFunnelGroupedParams,
    AnalyticsSearchReportParams,
    AnalyticsSearchGroupsParams,
    AnalyticsSearchDetailsParams,
    AnalyticsSearchTextsParams,
    AnalyticsSearchOrdersParams,
    AnalyticsStocksWbParams,
    AnalyticsStocksGroupsParams,
    AnalyticsStocksProductsParams,
    AnalyticsStocksSizesParams,
    AnalyticsStocksOfficesParams,
    AnalyticsCsvCreateParams,
    AnalyticsCsvRetryParams,
    # Reports
    ReportOrdersParams,
    ReportExciseParams,
    ReportBrandShareParams,
    FinanceReportDetailParams,
    ReportIdParams,
    # Finance
    DocIdParams,
    DocIdsParams,
    FinanceSalesReportsListParams,
    FinanceSalesReportByPeriodParams,
    FinanceAcquiringReportsListParams,
    FinanceAcquiringByPeriodParams,
    FinanceDocumentsListParams,
    # Users
    UserInviteParams,
    UserAccessUpdateParams,
    UserIdParams,
    # WBD
    WbdOfferIdParams,
    WbdKeysParams,
    WbdOfferUpdateParams,
    WbdOfferPriceParams,
    WbdOfferStatusParams,
    # File Downloads
    DownloadIdParams,
)


@dataclass(frozen=True, slots=True)
class Action:
    """Descriptor for a single server action (tool).

    Attributes:
        id:             Stable identifier, e.g. ``"wb_fbs_order_cancel"``.
        domain:         Logical grouping, e.g. ``"fbs_orders"``.
        description:    Short English description shown to the LLM.
        params_model:   Pydantic model for parameter validation, or ``None``.
        api_method:     Method name on :class:`WildberriesAPI` to call.
        is_destructive: ``True`` for delete / cancel operations.
        is_file:        ``True`` when the action returns raw bytes (downloads).
        keywords:       Search keywords (English + Russian) for discovery.
    """

    id: str
    domain: str
    description: str
    params_model: type[BaseModel] | None
    api_method: str
    is_destructive: bool = False
    is_file: bool = False
    keywords: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Action catalog -- 235 actions across 13 domains
# ---------------------------------------------------------------------------

_ACTIONS_LIST: list[Action] = [
    # ======================================================================
    # Domain: general  (9 actions)
    # ======================================================================
    Action(
        id="wb_ping",
        domain="general",
        description="Check Wildberries API availability",
        params_model=None,
        api_method="ping",
        keywords=["ping", "health", "проверка"],
    ),
    Action(
        id="wb_news",
        domain="general",
        description="Get seller portal news",
        params_model=None,
        api_method="get_news",
        keywords=["news", "новости"],
    ),
    Action(
        id="wb_seller_info",
        domain="general",
        description="Get seller name and profile ID",
        params_model=None,
        api_method="get_seller_info",
        keywords=["seller", "info", "продавец"],
    ),
    Action(
        id="wb_seller_rating",
        domain="general",
        description="Get seller rating",
        params_model=None,
        api_method="get_seller_rating",
        keywords=["rating", "рейтинг"],
    ),
    Action(
        id="wb_subscriptions",
        domain="general",
        description="Get notification subscriptions",
        params_model=None,
        api_method="get_subscriptions",
        keywords=["subscriptions", "подписки"],
    ),
    Action(
        id="wb_user_invite",
        domain="general",
        description="Create user invitation",
        params_model=UserInviteParams,
        api_method="create_user_invite",
        keywords=["user", "invite", "пригласить"],
    ),
    Action(
        id="wb_users",
        domain="general",
        description="Get list of users",
        params_model=None,
        api_method="get_users",
        keywords=["users", "пользователи"],
    ),
    Action(
        id="wb_user_access_update",
        domain="general",
        description="Update user access permissions",
        params_model=UserAccessUpdateParams,
        api_method="update_user_access",
        keywords=["user", "access", "permissions", "доступ"],
    ),
    Action(
        id="wb_user_delete",
        domain="general",
        description="Delete user",
        params_model=UserIdParams,
        api_method="delete_user",
        is_destructive=True,
        keywords=["user", "delete", "удалить"],
    ),

    # ======================================================================
    # Domain: content  (18 actions)
    # ======================================================================
    Action(
        id="wb_content_parent_categories",
        domain="content",
        description="Get parent categories",
        params_model=None,
        api_method="get_parent_categories",
        keywords=["categories", "категории"],
    ),
    Action(
        id="wb_content_subjects",
        domain="content",
        description="Get subjects (categories) list",
        params_model=SubjectsListParams,
        api_method="get_subjects",
        keywords=["subjects", "предметы", "категории"],
    ),
    Action(
        id="wb_content_characteristics",
        domain="content",
        description="Get subject characteristics",
        params_model=SubjectIdParams,
        api_method="get_characteristics",
        keywords=["characteristics", "характеристики"],
    ),
    Action(
        id="wb_content_colors",
        domain="content",
        description="Get color directory",
        params_model=None,
        api_method="get_colors",
        keywords=["colors", "цвета"],
    ),
    Action(
        id="wb_content_kinds",
        domain="content",
        description="Get gender directory",
        params_model=None,
        api_method="get_kinds",
        keywords=["kinds", "пол"],
    ),
    Action(
        id="wb_content_countries",
        domain="content",
        description="Get country directory",
        params_model=None,
        api_method="get_countries",
        keywords=["countries", "страны"],
    ),
    Action(
        id="wb_content_seasons",
        domain="content",
        description="Get season directory",
        params_model=None,
        api_method="get_seasons",
        keywords=["seasons", "сезоны"],
    ),
    Action(
        id="wb_content_vat",
        domain="content",
        description="Get VAT rates",
        params_model=None,
        api_method="get_vat",
        keywords=["vat", "НДС"],
    ),
    Action(
        id="wb_content_tnved",
        domain="content",
        description="Get TNVED codes for subject",
        params_model=SubjectIdParams,
        api_method="get_tnved",
        keywords=["tnved", "ТНВЭД"],
    ),
    Action(
        id="wb_content_brands",
        domain="content",
        description="Get brands",
        params_model=BrandsParams,
        api_method="get_brands",
        keywords=["brands", "бренды"],
    ),
    Action(
        id="wb_content_tags",
        domain="content",
        description="Get seller tags",
        params_model=None,
        api_method="get_tags",
        keywords=["tags", "теги"],
    ),
    Action(
        id="wb_content_tag_create",
        domain="content",
        description="Create tag",
        params_model=TagCreateParams,
        api_method="create_tag",
        keywords=["tag", "create", "создать"],
    ),
    Action(
        id="wb_content_tag_update",
        domain="content",
        description="Update tag",
        params_model=TagUpdateParams,
        api_method="update_tag",
        keywords=["tag", "update", "обновить"],
    ),
    Action(
        id="wb_content_tag_delete",
        domain="content",
        description="Delete tag",
        params_model=TagIdParams,
        api_method="delete_tag",
        is_destructive=True,
        keywords=["tag", "delete", "удалить"],
    ),
    Action(
        id="wb_content_tag_link",
        domain="content",
        description="Link tag to products",
        params_model=TagLinkParams,
        api_method="link_tags",
        keywords=["tag", "link", "привязать"],
    ),
    Action(
        id="wb_content_cards_list",
        domain="content",
        description="Get product cards list",
        params_model=CardsListParams,
        api_method="get_cards_list",
        keywords=["cards", "products", "карточки", "товары"],
    ),
    Action(
        id="wb_content_cards_errors",
        domain="content",
        description="Get card upload errors",
        params_model=None,
        api_method="get_cards_errors",
        keywords=["cards", "errors", "ошибки"],
    ),
    Action(
        id="wb_content_cards_update",
        domain="content",
        description="Update product cards",
        params_model=CardsUpdateParams,
        api_method="update_cards",
        keywords=["cards", "update", "обновить"],
    ),

    # ======================================================================
    # Domain: fbs_orders  (31 actions)
    # ======================================================================
    Action(
        id="wb_fbs_orders_new",
        domain="fbs_orders",
        description="Get new FBS assembly orders",
        params_model=None,
        api_method="get_fbs_orders_new",
        keywords=["fbs", "orders", "new", "заказы"],
    ),
    Action(
        id="wb_fbs_orders",
        domain="fbs_orders",
        description="Get FBS orders",
        params_model=FbsOrdersParams,
        api_method="get_fbs_orders",
        keywords=["fbs", "orders", "заказы"],
    ),
    Action(
        id="wb_fbs_orders_status",
        domain="fbs_orders",
        description="Get FBS order statuses",
        params_model=OrderIdsParams,
        api_method="get_fbs_orders_status",
        keywords=["fbs", "orders", "status", "статус"],
    ),
    Action(
        id="wb_fbs_order_cancel",
        domain="fbs_orders",
        description="Cancel FBS order",
        params_model=OrderIdParams,
        api_method="cancel_fbs_order",
        is_destructive=True,
        keywords=["fbs", "order", "cancel", "отмена"],
    ),
    Action(
        id="wb_fbs_stickers",
        domain="fbs_orders",
        description="Get FBS order stickers",
        params_model=FbsStickersParams,
        api_method="get_fbs_stickers",
        keywords=["fbs", "stickers", "стикеры"],
    ),
    Action(
        id="wb_fbs_stickers_cross_border",
        domain="fbs_orders",
        description="Get cross-border stickers",
        params_model=OrderIdsParams,
        api_method="get_fbs_stickers_cross_border",
        keywords=["fbs", "stickers", "cross-border"],
    ),
    Action(
        id="wb_fbs_orders_status_history",
        domain="fbs_orders",
        description="Get FBS order status history",
        params_model=OrderIdsParams,
        api_method="get_fbs_orders_status_history",
        keywords=["fbs", "orders", "status", "history", "история"],
    ),
    Action(
        id="wb_fbs_orders_client",
        domain="fbs_orders",
        description="Get FBS order client info",
        params_model=OrderIdsParams,
        api_method="get_fbs_orders_client",
        keywords=["fbs", "orders", "client", "клиент"],
    ),
    Action(
        id="wb_fbs_reshipment_orders",
        domain="fbs_orders",
        description="Get FBS reshipment orders",
        params_model=None,
        api_method="get_fbs_reshipment_orders",
        keywords=["fbs", "reshipment", "перевозка"],
    ),
    Action(
        id="wb_fbs_order_meta",
        domain="fbs_orders",
        description="Get FBS order metadata",
        params_model=OrderIdsParams,
        api_method="get_fbs_order_meta",
        keywords=["fbs", "meta", "метаданные"],
    ),
    Action(
        id="wb_fbs_order_meta_delete",
        domain="fbs_orders",
        description="Delete FBS order metadata",
        params_model=OrderIdParams,
        api_method="delete_fbs_order_meta",
        is_destructive=True,
        keywords=["fbs", "meta", "delete"],
    ),
    Action(
        id="wb_fbs_order_meta_sgtin",
        domain="fbs_orders",
        description="Set Honest Sign codes for FBS order",
        params_model=OrderSgtinParams,
        api_method="set_fbs_order_sgtin",
        keywords=["fbs", "meta", "sgtin", "честный знак"],
    ),
    Action(
        id="wb_fbs_order_meta_uin",
        domain="fbs_orders",
        description="Set UIN for FBS order",
        params_model=OrderUinParams,
        api_method="set_fbs_order_uin",
        keywords=["fbs", "meta", "uin", "УИН"],
    ),
    Action(
        id="wb_fbs_order_meta_imei",
        domain="fbs_orders",
        description="Set IMEI for FBS order",
        params_model=OrderImeiParams,
        api_method="set_fbs_order_imei",
        keywords=["fbs", "meta", "imei"],
    ),
    Action(
        id="wb_fbs_order_meta_gtin",
        domain="fbs_orders",
        description="Set GTIN for FBS order",
        params_model=OrderGtinParams,
        api_method="set_fbs_order_gtin",
        keywords=["fbs", "meta", "gtin"],
    ),
    Action(
        id="wb_fbs_order_meta_expiration",
        domain="fbs_orders",
        description="Set expiration date for FBS order",
        params_model=OrderExpirationParams,
        api_method="set_fbs_order_expiration",
        keywords=["fbs", "meta", "expiration", "годность"],
    ),
    Action(
        id="wb_fbs_order_meta_customs",
        domain="fbs_orders",
        description="Set customs declaration for FBS order",
        params_model=OrderCustomsParams,
        api_method="set_fbs_order_customs",
        keywords=["fbs", "meta", "customs", "таможня"],
    ),
    Action(
        id="wb_fbs_supply_create",
        domain="fbs_orders",
        description="Create FBS supply",
        params_model=FbsSupplyCreateParams,
        api_method="create_fbs_supply",
        keywords=["fbs", "supply", "create", "поставка"],
    ),
    Action(
        id="wb_fbs_supplies",
        domain="fbs_orders",
        description="Get FBS supplies list",
        params_model=FbsSuppliesParams,
        api_method="get_fbs_supplies",
        keywords=["fbs", "supplies", "поставки"],
    ),
    Action(
        id="wb_fbs_supply_add_orders",
        domain="fbs_orders",
        description="Add orders to FBS supply",
        params_model=FbsSupplyAddOrdersParams,
        api_method="add_fbs_supply_orders",
        keywords=["fbs", "supply", "orders", "добавить"],
    ),
    Action(
        id="wb_fbs_supply",
        domain="fbs_orders",
        description="Get FBS supply details",
        params_model=SupplyIdParams,
        api_method="get_fbs_supply",
        keywords=["fbs", "supply", "поставка"],
    ),
    Action(
        id="wb_fbs_supply_delete",
        domain="fbs_orders",
        description="Delete FBS supply",
        params_model=SupplyIdParams,
        api_method="delete_fbs_supply",
        is_destructive=True,
        keywords=["fbs", "supply", "delete", "удалить"],
    ),
    Action(
        id="wb_fbs_supply_orders",
        domain="fbs_orders",
        description="Get FBS supply order IDs",
        params_model=SupplyIdParams,
        api_method="get_fbs_supply_orders",
        keywords=["fbs", "supply", "orders"],
    ),
    Action(
        id="wb_fbs_supply_deliver",
        domain="fbs_orders",
        description="Deliver FBS supply",
        params_model=SupplyIdParams,
        api_method="deliver_fbs_supply",
        keywords=["fbs", "supply", "deliver", "доставка"],
    ),
    Action(
        id="wb_fbs_supply_barcode",
        domain="fbs_orders",
        description="Get FBS supply barcode",
        params_model=SupplyIdParams,
        api_method="get_fbs_supply_barcode",
        keywords=["fbs", "supply", "barcode", "штрихкод"],
    ),
    Action(
        id="wb_fbs_supply_boxes",
        domain="fbs_orders",
        description="Get FBS supply boxes",
        params_model=SupplyIdParams,
        api_method="get_fbs_supply_boxes",
        keywords=["fbs", "supply", "boxes", "коробки"],
    ),
    Action(
        id="wb_fbs_pass_offices",
        domain="fbs_orders",
        description="Get warehouses requiring access pass",
        params_model=None,
        api_method="get_fbs_pass_offices",
        keywords=["fbs", "pass", "offices", "пропуск"],
    ),
    Action(
        id="wb_fbs_passes",
        domain="fbs_orders",
        description="Get all access passes",
        params_model=None,
        api_method="get_fbs_passes",
        keywords=["fbs", "passes", "пропуска"],
    ),
    Action(
        id="wb_fbs_pass_create",
        domain="fbs_orders",
        description="Create access pass",
        params_model=FbsPassCreateParams,
        api_method="create_fbs_pass",
        keywords=["fbs", "pass", "create", "пропуск"],
    ),
    Action(
        id="wb_fbs_pass_update",
        domain="fbs_orders",
        description="Update access pass",
        params_model=FbsPassUpdateParams,
        api_method="update_fbs_pass",
        keywords=["fbs", "pass", "update"],
    ),
    Action(
        id="wb_fbs_pass_delete",
        domain="fbs_orders",
        description="Delete access pass",
        params_model=PassIdParams,
        api_method="delete_fbs_pass",
        is_destructive=True,
        keywords=["fbs", "pass", "delete"],
    ),

    # ======================================================================
    # Domain: dbw_orders  (16 actions)
    # ======================================================================
    Action(
        id="wb_dbw_orders_new",
        domain="dbw_orders",
        description="Get new DBW assembly tasks",
        params_model=None,
        api_method="get_dbw_orders_new",
        keywords=["dbw", "orders", "new"],
    ),
    Action(
        id="wb_dbw_orders",
        domain="dbw_orders",
        description="Get completed DBW assembly tasks",
        params_model=None,
        api_method="get_dbw_orders",
        keywords=["dbw", "orders", "completed"],
    ),
    Action(
        id="wb_dbw_delivery_date",
        domain="dbw_orders",
        description="Get DBW delivery dates",
        params_model=OrderIdsParams,
        api_method="get_dbw_delivery_date",
        keywords=["dbw", "delivery", "date"],
    ),
    Action(
        id="wb_dbw_client",
        domain="dbw_orders",
        description="Get DBW client info",
        params_model=OrderIdsParams,
        api_method="get_dbw_client",
        keywords=["dbw", "client", "клиент"],
    ),
    Action(
        id="wb_dbw_orders_status",
        domain="dbw_orders",
        description="Get DBW order statuses",
        params_model=OrderIdsParams,
        api_method="get_dbw_orders_status",
        keywords=["dbw", "orders", "status"],
    ),
    Action(
        id="wb_dbw_order_confirm",
        domain="dbw_orders",
        description="Confirm DBW order",
        params_model=OrderIdParams,
        api_method="confirm_dbw_order",
        keywords=["dbw", "confirm", "подтвердить"],
    ),
    Action(
        id="wb_dbw_stickers",
        domain="dbw_orders",
        description="Get DBW stickers",
        params_model=OrderIdsParams,
        api_method="get_dbw_stickers",
        keywords=["dbw", "stickers"],
    ),
    Action(
        id="wb_dbw_order_assemble",
        domain="dbw_orders",
        description="Move DBW order to delivery",
        params_model=OrderIdParams,
        api_method="assemble_dbw_order",
        keywords=["dbw", "assemble", "delivery"],
    ),
    Action(
        id="wb_dbw_courier",
        domain="dbw_orders",
        description="Get DBW courier info",
        params_model=OrderIdsParams,
        api_method="get_dbw_courier",
        keywords=["dbw", "courier", "курьер"],
    ),
    Action(
        id="wb_dbw_order_cancel",
        domain="dbw_orders",
        description="Cancel DBW order",
        params_model=OrderIdParams,
        api_method="cancel_dbw_order",
        is_destructive=True,
        keywords=["dbw", "cancel", "отмена"],
    ),
    Action(
        id="wb_dbw_order_meta",
        domain="dbw_orders",
        description="Get DBW order metadata",
        params_model=OrderIdParams,
        api_method="get_dbw_order_meta",
        keywords=["dbw", "meta"],
    ),
    Action(
        id="wb_dbw_order_meta_delete",
        domain="dbw_orders",
        description="Delete DBW order metadata",
        params_model=OrderIdParams,
        api_method="delete_dbw_order_meta",
        is_destructive=True,
        keywords=["dbw", "meta", "delete"],
    ),
    Action(
        id="wb_dbw_order_meta_sgtin",
        domain="dbw_orders",
        description="Set Honest Sign codes for DBW order",
        params_model=OrderSgtinParams,
        api_method="set_dbw_order_sgtin",
        keywords=["dbw", "meta", "sgtin"],
    ),
    Action(
        id="wb_dbw_order_meta_uin",
        domain="dbw_orders",
        description="Set UIN for DBW order",
        params_model=OrderUinParams,
        api_method="set_dbw_order_uin",
        keywords=["dbw", "meta", "uin"],
    ),
    Action(
        id="wb_dbw_order_meta_imei",
        domain="dbw_orders",
        description="Set IMEI for DBW order",
        params_model=OrderImeiParams,
        api_method="set_dbw_order_imei",
        keywords=["dbw", "meta", "imei"],
    ),
    Action(
        id="wb_dbw_order_meta_gtin",
        domain="dbw_orders",
        description="Set GTIN for DBW order",
        params_model=OrderGtinParams,
        api_method="set_dbw_order_gtin",
        keywords=["dbw", "meta", "gtin"],
    ),

    # ======================================================================
    # Domain: dbs_orders  (20 actions)
    # ======================================================================
    Action(
        id="wb_dbs_orders_new",
        domain="dbs_orders",
        description="Get new DBS orders",
        params_model=None,
        api_method="get_dbs_orders_new",
        keywords=["dbs", "orders", "new"],
    ),
    Action(
        id="wb_dbs_orders",
        domain="dbs_orders",
        description="Get completed DBS orders",
        params_model=None,
        api_method="get_dbs_orders",
        keywords=["dbs", "orders"],
    ),
    Action(
        id="wb_dbs_groups_info",
        domain="dbs_orders",
        description="Get DBS paid delivery info",
        params_model=OrderIdsParams,
        api_method="get_dbs_groups_info",
        keywords=["dbs", "groups", "delivery"],
    ),
    Action(
        id="wb_dbs_client",
        domain="dbs_orders",
        description="Get DBS client info",
        params_model=OrderIdsParams,
        api_method="get_dbs_client",
        keywords=["dbs", "client"],
    ),
    Action(
        id="wb_dbs_b2b_info",
        domain="dbs_orders",
        description="Get DBS B2B buyer info",
        params_model=OrderIdsParams,
        api_method="get_dbs_b2b_info",
        keywords=["dbs", "b2b"],
    ),
    Action(
        id="wb_dbs_delivery_date",
        domain="dbs_orders",
        description="Get DBS delivery dates",
        params_model=OrderIdsParams,
        api_method="get_dbs_delivery_date",
        keywords=["dbs", "delivery", "date"],
    ),
    Action(
        id="wb_dbs_orders_status",
        domain="dbs_orders",
        description="Get DBS order statuses",
        params_model=OrderIdsParams,
        api_method="get_dbs_orders_status",
        keywords=["dbs", "status"],
    ),
    Action(
        id="wb_dbs_order_cancel",
        domain="dbs_orders",
        description="Cancel DBS order",
        params_model=OrderIdsParams,
        api_method="cancel_dbs_order",
        is_destructive=True,
        keywords=["dbs", "cancel"],
    ),
    Action(
        id="wb_dbs_order_confirm",
        domain="dbs_orders",
        description="Confirm DBS order",
        params_model=OrderIdsParams,
        api_method="confirm_dbs_order",
        keywords=["dbs", "confirm"],
    ),
    Action(
        id="wb_dbs_stickers",
        domain="dbs_orders",
        description="Get DBS stickers",
        params_model=OrderIdsParams,
        api_method="get_dbs_stickers",
        keywords=["dbs", "stickers"],
    ),
    Action(
        id="wb_dbs_order_deliver",
        domain="dbs_orders",
        description="Move DBS order to delivery",
        params_model=OrderIdsParams,
        api_method="deliver_dbs_order",
        keywords=["dbs", "deliver"],
    ),
    Action(
        id="wb_dbs_order_receive",
        domain="dbs_orders",
        description="Confirm DBS order receipt",
        params_model=OrderIdsParams,
        api_method="receive_dbs_order",
        keywords=["dbs", "receive"],
    ),
    Action(
        id="wb_dbs_order_reject",
        domain="dbs_orders",
        description="Record DBS order rejection",
        params_model=OrderIdsParams,
        api_method="reject_dbs_order",
        keywords=["dbs", "reject"],
    ),
    Action(
        id="wb_dbs_order_meta",
        domain="dbs_orders",
        description="Get DBS order metadata",
        params_model=OrderIdsParams,
        api_method="get_dbs_order_meta",
        keywords=["dbs", "meta"],
    ),
    Action(
        id="wb_dbs_order_meta_delete",
        domain="dbs_orders",
        description="Delete DBS order metadata",
        params_model=OrderIdsParams,
        api_method="delete_dbs_order_meta",
        is_destructive=True,
        keywords=["dbs", "meta", "delete"],
    ),
    Action(
        id="wb_dbs_order_meta_sgtin",
        domain="dbs_orders",
        description="Set Honest Sign codes for DBS orders",
        params_model=OrdersBatchParams,
        api_method="set_dbs_order_sgtin",
        keywords=["dbs", "meta", "sgtin"],
    ),
    Action(
        id="wb_dbs_order_meta_uin",
        domain="dbs_orders",
        description="Set UIN for DBS orders",
        params_model=OrdersBatchParams,
        api_method="set_dbs_order_uin",
        keywords=["dbs", "meta", "uin"],
    ),
    Action(
        id="wb_dbs_order_meta_imei",
        domain="dbs_orders",
        description="Set IMEI for DBS orders",
        params_model=OrdersBatchParams,
        api_method="set_dbs_order_imei",
        keywords=["dbs", "meta", "imei"],
    ),
    Action(
        id="wb_dbs_order_meta_gtin",
        domain="dbs_orders",
        description="Set GTIN for DBS orders",
        params_model=OrdersBatchParams,
        api_method="set_dbs_order_gtin",
        keywords=["dbs", "meta", "gtin"],
    ),
    Action(
        id="wb_dbs_order_meta_customs",
        domain="dbs_orders",
        description="Set customs for DBS orders",
        params_model=OrdersBatchParams,
        api_method="set_dbs_order_customs",
        keywords=["dbs", "meta", "customs"],
    ),

    # ======================================================================
    # Domain: pickup_orders  (16 actions)
    # ======================================================================
    Action(
        id="wb_pickup_orders_new",
        domain="pickup_orders",
        description="Get new pickup orders",
        params_model=None,
        api_method="get_pickup_orders_new",
        keywords=["pickup", "orders", "new", "самовывоз"],
    ),
    Action(
        id="wb_pickup_order_confirm",
        domain="pickup_orders",
        description="Confirm pickup order",
        params_model=OrderIdsParams,
        api_method="confirm_pickup_order",
        keywords=["pickup", "confirm"],
    ),
    Action(
        id="wb_pickup_order_prepare",
        domain="pickup_orders",
        description="Mark pickup order as ready",
        params_model=OrderIdsParams,
        api_method="prepare_pickup_order",
        keywords=["pickup", "prepare"],
    ),
    Action(
        id="wb_pickup_client",
        domain="pickup_orders",
        description="Get pickup client info",
        params_model=OrderIdsParams,
        api_method="get_pickup_client",
        keywords=["pickup", "client"],
    ),
    Action(
        id="wb_pickup_verify_identity",
        domain="pickup_orders",
        description="Verify pickup order ownership",
        params_model=OrderIdsParams,
        api_method="verify_pickup_identity",
        keywords=["pickup", "verify"],
    ),
    Action(
        id="wb_pickup_order_receive",
        domain="pickup_orders",
        description="Confirm pickup receipt",
        params_model=OrderIdsParams,
        api_method="receive_pickup_order",
        keywords=["pickup", "receive"],
    ),
    Action(
        id="wb_pickup_order_reject",
        domain="pickup_orders",
        description="Record pickup rejection",
        params_model=OrderIdsParams,
        api_method="reject_pickup_order",
        keywords=["pickup", "reject"],
    ),
    Action(
        id="wb_pickup_orders_status",
        domain="pickup_orders",
        description="Get pickup order statuses",
        params_model=OrderIdsParams,
        api_method="get_pickup_orders_status",
        keywords=["pickup", "status"],
    ),
    Action(
        id="wb_pickup_orders_completed",
        domain="pickup_orders",
        description="Get completed pickup orders",
        params_model=None,
        api_method="get_pickup_orders_completed",
        keywords=["pickup", "completed"],
    ),
    Action(
        id="wb_pickup_order_cancel",
        domain="pickup_orders",
        description="Cancel pickup order",
        params_model=OrderIdsParams,
        api_method="cancel_pickup_order",
        is_destructive=True,
        keywords=["pickup", "cancel"],
    ),
    Action(
        id="wb_pickup_order_meta",
        domain="pickup_orders",
        description="Get pickup order metadata",
        params_model=OrderIdsParams,
        api_method="get_pickup_order_meta",
        keywords=["pickup", "meta"],
    ),
    Action(
        id="wb_pickup_order_meta_delete",
        domain="pickup_orders",
        description="Delete pickup order metadata",
        params_model=OrderIdsParams,
        api_method="delete_pickup_order_meta",
        is_destructive=True,
        keywords=["pickup", "meta", "delete"],
    ),
    Action(
        id="wb_pickup_order_meta_sgtin",
        domain="pickup_orders",
        description="Set Honest Sign codes for pickup orders",
        params_model=OrdersBatchParams,
        api_method="set_pickup_order_sgtin",
        keywords=["pickup", "meta", "sgtin"],
    ),
    Action(
        id="wb_pickup_order_meta_uin",
        domain="pickup_orders",
        description="Set UIN for pickup orders",
        params_model=OrdersBatchParams,
        api_method="set_pickup_order_uin",
        keywords=["pickup", "meta", "uin"],
    ),
    Action(
        id="wb_pickup_order_meta_imei",
        domain="pickup_orders",
        description="Set IMEI for pickup orders",
        params_model=OrdersBatchParams,
        api_method="set_pickup_order_imei",
        keywords=["pickup", "meta", "imei"],
    ),
    Action(
        id="wb_pickup_order_meta_gtin",
        domain="pickup_orders",
        description="Set GTIN for pickup orders",
        params_model=OrdersBatchParams,
        api_method="set_pickup_order_gtin",
        keywords=["pickup", "meta", "gtin"],
    ),

    # ======================================================================
    # Domain: fbw_supplies  (7 actions)
    # ======================================================================
    Action(
        id="wb_fbw_acceptance_options",
        domain="fbw_supplies",
        description="Get FBW warehouse acceptance options",
        params_model=FbwAcceptanceOptionsParams,
        api_method="get_fbw_acceptance_options",
        keywords=["fbw", "acceptance"],
    ),
    Action(
        id="wb_fbw_warehouses",
        domain="fbw_supplies",
        description="Get Wildberries warehouse list",
        params_model=None,
        api_method="get_fbw_warehouses",
        keywords=["fbw", "warehouses", "склады"],
    ),
    Action(
        id="wb_fbw_transit_tariffs",
        domain="fbw_supplies",
        description="Get transit tariffs",
        params_model=None,
        api_method="get_fbw_transit_tariffs",
        keywords=["fbw", "transit", "tariffs"],
    ),
    Action(
        id="wb_fbw_supplies",
        domain="fbw_supplies",
        description="Get FBW supplies list",
        params_model=FbwSuppliesFilterParams,
        api_method="get_fbw_supplies",
        keywords=["fbw", "supplies", "поставки"],
    ),
    Action(
        id="wb_fbw_supply",
        domain="fbw_supplies",
        description="Get FBW supply details",
        params_model=SupplyIdParams,
        api_method="get_fbw_supply",
        keywords=["fbw", "supply"],
    ),
    Action(
        id="wb_fbw_supply_goods",
        domain="fbw_supplies",
        description="Get FBW supply goods",
        params_model=SupplyIdParams,
        api_method="get_fbw_supply_goods",
        keywords=["fbw", "supply", "goods"],
    ),
    Action(
        id="wb_fbw_supply_package",
        domain="fbw_supplies",
        description="Get FBW supply package info",
        params_model=SupplyIdParams,
        api_method="get_fbw_supply_package",
        keywords=["fbw", "supply", "package"],
    ),

    # ======================================================================
    # Domain: advertising  (26 actions)
    # ======================================================================
    Action(
        id="wb_advert_campaigns_count",
        domain="advertising",
        description="Get advertising campaign counts",
        params_model=None,
        api_method="get_advert_campaigns_count",
        keywords=["advert", "campaigns", "count"],
    ),
    Action(
        id="wb_advert_campaigns",
        domain="advertising",
        description="Get advertising campaign details",
        params_model=CampaignIdsParams,
        api_method="get_advert_campaigns",
        keywords=["advert", "campaigns"],
    ),
    Action(
        id="wb_advert_min_bids",
        domain="advertising",
        description="Get minimum bid rates",
        params_model=AdvertMinBidsParams,
        api_method="get_advert_min_bids",
        keywords=["advert", "bids", "min"],
    ),
    Action(
        id="wb_advert_campaign_create",
        domain="advertising",
        description="Create advertising campaign",
        params_model=AdvertCampaignCreateParams,
        api_method="create_advert_campaign",
        keywords=["advert", "campaign", "create"],
    ),
    Action(
        id="wb_advert_subjects",
        domain="advertising",
        description="Get available categories for advertising",
        params_model=None,
        api_method="get_advert_subjects",
        keywords=["advert", "subjects"],
    ),
    Action(
        id="wb_advert_nms",
        domain="advertising",
        description="Get product cards for advertising",
        params_model=AdvertNmsParams,
        api_method="get_advert_nms",
        keywords=["advert", "nms", "cards"],
    ),
    Action(
        id="wb_advert_campaign_delete",
        domain="advertising",
        description="Delete advertising campaign",
        params_model=CampaignIdParams,
        api_method="delete_advert_campaign",
        is_destructive=True,
        keywords=["advert", "campaign", "delete"],
    ),
    Action(
        id="wb_advert_campaign_rename",
        domain="advertising",
        description="Rename advertising campaign",
        params_model=CampaignRenameParams,
        api_method="rename_advert_campaign",
        keywords=["advert", "campaign", "rename"],
    ),
    Action(
        id="wb_advert_campaign_start",
        domain="advertising",
        description="Start advertising campaign",
        params_model=CampaignIdParams,
        api_method="start_advert_campaign",
        keywords=["advert", "campaign", "start"],
    ),
    Action(
        id="wb_advert_campaign_pause",
        domain="advertising",
        description="Pause advertising campaign",
        params_model=CampaignIdParams,
        api_method="pause_advert_campaign",
        keywords=["advert", "campaign", "pause"],
    ),
    Action(
        id="wb_advert_campaign_stop",
        domain="advertising",
        description="Stop advertising campaign",
        params_model=CampaignIdParams,
        api_method="stop_advert_campaign",
        keywords=["advert", "campaign", "stop"],
    ),
    Action(
        id="wb_advert_placements_update",
        domain="advertising",
        description="Update advertising placements",
        params_model=AdvertPlacementsUpdateParams,
        api_method="update_advert_placements",
        keywords=["advert", "placements"],
    ),
    Action(
        id="wb_advert_bids_update",
        domain="advertising",
        description="Update advertising bids",
        params_model=AdvertBidsUpdateParams,
        api_method="update_advert_bids",
        keywords=["advert", "bids", "update"],
    ),
    Action(
        id="wb_advert_nms_update",
        domain="advertising",
        description="Manage product cards in campaign",
        params_model=AdvertNmsUpdateParams,
        api_method="update_advert_nms",
        keywords=["advert", "nms", "update"],
    ),
    Action(
        id="wb_advert_bid_recommendations",
        domain="advertising",
        description="Get bid recommendations",
        params_model=CampaignIdParams,
        api_method="get_advert_bid_recommendations",
        keywords=["advert", "bids", "recommendations"],
    ),
    Action(
        id="wb_advert_search_bids",
        domain="advertising",
        description="Get search cluster bids",
        params_model=AdvertSearchBidsGetParams,
        api_method="get_advert_search_bids",
        keywords=["advert", "search", "bids"],
    ),
    Action(
        id="wb_advert_search_bids_set",
        domain="advertising",
        description="Set search cluster bids",
        params_model=AdvertSearchBidsSetParams,
        api_method="set_advert_search_bids",
        keywords=["advert", "search", "bids", "set"],
    ),
    Action(
        id="wb_advert_search_bids_delete",
        domain="advertising",
        description="Delete search cluster bids",
        params_model=AdvertSearchBidsSetParams,
        api_method="delete_advert_search_bids",
        is_destructive=True,
        keywords=["advert", "search", "bids", "delete"],
    ),
    Action(
        id="wb_advert_minus_phrases",
        domain="advertising",
        description="Get negative phrases",
        params_model=AdvertMinusPhraseGetParams,
        api_method="get_advert_minus_phrases",
        keywords=["advert", "minus", "phrases"],
    ),
    Action(
        id="wb_advert_minus_phrases_set",
        domain="advertising",
        description="Set negative phrases",
        params_model=AdvertMinusPhraseSetParams,
        api_method="set_advert_minus_phrases",
        keywords=["advert", "minus", "phrases", "set"],
    ),
    Action(
        id="wb_advert_balance",
        domain="advertising",
        description="Get advertising account balance",
        params_model=None,
        api_method="get_advert_balance",
        keywords=["advert", "balance"],
    ),
    Action(
        id="wb_advert_budget",
        domain="advertising",
        description="Get advertising campaign budget",
        params_model=CampaignIdParams,
        api_method="get_advert_budget",
        keywords=["advert", "budget"],
    ),
    Action(
        id="wb_advert_budget_deposit",
        domain="advertising",
        description="Replenish campaign budget",
        params_model=CampaignBudgetDepositParams,
        api_method="deposit_advert_budget",
        keywords=["advert", "budget", "deposit"],
    ),
    Action(
        id="wb_advert_cost_history",
        domain="advertising",
        description="Get advertising cost history",
        params_model=AdvertDateRangeParams,
        api_method="get_advert_cost_history",
        keywords=["advert", "cost", "history"],
    ),
    Action(
        id="wb_advert_payments",
        domain="advertising",
        description="Get advertising payment history",
        params_model=AdvertDateRangeParams,
        api_method="get_advert_payments",
        keywords=["advert", "payments"],
    ),
    Action(
        id="wb_advert_search_stats",
        domain="advertising",
        description="Get search cluster statistics",
        params_model=AdvertSearchStatsParams,
        api_method="get_advert_search_stats",
        keywords=["advert", "search", "stats"],
    ),

    # ======================================================================
    # Domain: communications  (22 actions)
    # ======================================================================
    Action(
        id="wb_new_feedbacks_questions",
        domain="communications",
        description="Get count of unread questions and reviews",
        params_model=None,
        api_method="get_new_feedbacks_questions",
        keywords=["feedbacks", "questions", "count"],
    ),
    Action(
        id="wb_questions_unanswered_count",
        domain="communications",
        description="Get count of unanswered questions",
        params_model=None,
        api_method="get_unanswered_questions_count",
        keywords=["questions", "unanswered"],
    ),
    Action(
        id="wb_questions_count",
        domain="communications",
        description="Get question count for period",
        params_model=QuestionsCountParams,
        api_method="get_questions_count",
        keywords=["questions", "count"],
    ),
    Action(
        id="wb_questions",
        domain="communications",
        description="Get questions list",
        params_model=QuestionsParams,
        api_method="get_questions",
        keywords=["questions", "вопросы"],
    ),
    Action(
        id="wb_question_manage",
        domain="communications",
        description="Manage question (answer, reject, view)",
        params_model=QuestionManageParams,
        api_method="manage_question",
        keywords=["question", "answer", "manage"],
    ),
    Action(
        id="wb_question",
        domain="communications",
        description="Get individual question",
        params_model=QuestionIdParams,
        api_method="get_question",
        keywords=["question"],
    ),
    Action(
        id="wb_feedbacks_unanswered_count",
        domain="communications",
        description="Get count of unprocessed reviews",
        params_model=None,
        api_method="get_unanswered_feedbacks_count",
        keywords=["feedbacks", "unanswered"],
    ),
    Action(
        id="wb_feedbacks_count",
        domain="communications",
        description="Get review count for period",
        params_model=FeedbacksCountParams,
        api_method="get_feedbacks_count",
        keywords=["feedbacks", "count"],
    ),
    Action(
        id="wb_feedbacks",
        domain="communications",
        description="Get reviews list",
        params_model=FeedbacksParams,
        api_method="get_feedbacks",
        keywords=["feedbacks", "отзывы"],
    ),
    Action(
        id="wb_feedback_answer",
        domain="communications",
        description="Answer review",
        params_model=FeedbackAnswerParams,
        api_method="answer_feedback",
        keywords=["feedback", "answer", "ответ"],
    ),
    Action(
        id="wb_feedback_answer_edit",
        domain="communications",
        description="Edit review answer",
        params_model=FeedbackAnswerParams,
        api_method="edit_feedback_answer",
        keywords=["feedback", "answer", "edit"],
    ),
    Action(
        id="wb_feedback_return",
        domain="communications",
        description="Request return for review",
        params_model=FeedbackIdParams,
        api_method="request_feedback_return",
        keywords=["feedback", "return", "возврат"],
    ),
    Action(
        id="wb_feedback",
        domain="communications",
        description="Get individual review",
        params_model=FeedbackIdParams,
        api_method="get_feedback",
        keywords=["feedback", "отзыв"],
    ),
    Action(
        id="wb_feedbacks_archive",
        domain="communications",
        description="Get archived reviews",
        params_model=FeedbacksArchiveParams,
        api_method="get_feedbacks_archive",
        keywords=["feedbacks", "archive"],
    ),
    Action(
        id="wb_feedback_pins",
        domain="communications",
        description="Get pinned reviews for product",
        params_model=NmIdParams,
        api_method="get_pinned_feedbacks",
        keywords=["feedback", "pins"],
    ),
    Action(
        id="wb_feedback_pin",
        domain="communications",
        description="Pin review",
        params_model=FeedbackPinParams,
        api_method="pin_feedback",
        keywords=["feedback", "pin"],
    ),
    Action(
        id="wb_feedback_unpin",
        domain="communications",
        description="Unpin review",
        params_model=FeedbackPinParams,
        api_method="unpin_feedback",
        keywords=["feedback", "unpin"],
    ),
    Action(
        id="wb_feedback_pins_count",
        domain="communications",
        description="Get pinned review count",
        params_model=NmIdParams,
        api_method="get_pinned_feedbacks_count",
        keywords=["feedback", "pins", "count"],
    ),
    Action(
        id="wb_feedback_pins_limits",
        domain="communications",
        description="Get pinning limits",
        params_model=None,
        api_method="get_pinned_feedbacks_limits",
        keywords=["feedback", "pins", "limits"],
    ),
    Action(
        id="wb_chats",
        domain="communications",
        description="Get chats list",
        params_model=None,
        api_method="get_chats",
        keywords=["chats", "чаты"],
    ),
    Action(
        id="wb_chat_events",
        domain="communications",
        description="Get chat events",
        params_model=None,
        api_method="get_chat_events",
        keywords=["chat", "events"],
    ),
    Action(
        id="wb_chat_send",
        domain="communications",
        description="Send chat message",
        params_model=ChatSendParams,
        api_method="send_chat_message",
        keywords=["chat", "send", "отправить"],
    ),

    # ======================================================================
    # Domain: tariffs  (5 actions)
    # ======================================================================
    Action(
        id="wb_tariff_commissions",
        domain="tariffs",
        description="Get commission rates",
        params_model=None,
        api_method="get_tariff_commissions",
        keywords=["tariff", "commissions", "комиссии"],
    ),
    Action(
        id="wb_tariff_box",
        domain="tariffs",
        description="Get box delivery tariffs",
        params_model=TariffDateParams,
        api_method="get_tariff_box",
        keywords=["tariff", "box"],
    ),
    Action(
        id="wb_tariff_pallet",
        domain="tariffs",
        description="Get pallet tariffs",
        params_model=TariffDateParams,
        api_method="get_tariff_pallet",
        keywords=["tariff", "pallet"],
    ),
    Action(
        id="wb_tariff_acceptance",
        domain="tariffs",
        description="Get acceptance coefficients",
        params_model=None,
        api_method="get_tariff_acceptance",
        keywords=["tariff", "acceptance"],
    ),
    Action(
        id="wb_tariff_return",
        domain="tariffs",
        description="Get return tariffs",
        params_model=None,
        api_method="get_tariff_return",
        keywords=["tariff", "return"],
    ),

    # ======================================================================
    # Domain: analytics  (17 actions)
    # ======================================================================
    Action(
        id="wb_analytics_sales_funnel",
        domain="analytics",
        description="Get product sales funnel",
        params_model=AnalyticsSalesFunnelParams,
        api_method="get_analytics_sales_funnel",
        keywords=["analytics", "funnel", "воронка"],
    ),
    Action(
        id="wb_analytics_sales_funnel_history",
        domain="analytics",
        description="Get sales funnel history",
        params_model=AnalyticsSalesFunnelHistoryParams,
        api_method="get_analytics_sales_funnel_history",
        keywords=["analytics", "funnel", "history"],
    ),
    Action(
        id="wb_analytics_sales_funnel_grouped",
        domain="analytics",
        description="Get grouped sales funnel",
        params_model=AnalyticsSalesFunnelGroupedParams,
        api_method="get_analytics_sales_funnel_grouped",
        keywords=["analytics", "funnel", "grouped"],
    ),
    Action(
        id="wb_analytics_search_report",
        domain="analytics",
        description="Get search queries report",
        params_model=AnalyticsSearchReportParams,
        api_method="get_analytics_search_report",
        keywords=["analytics", "search", "report"],
    ),
    Action(
        id="wb_analytics_search_groups",
        domain="analytics",
        description="Get search query groups",
        params_model=AnalyticsSearchGroupsParams,
        api_method="get_analytics_search_groups",
        keywords=["analytics", "search", "groups"],
    ),
    Action(
        id="wb_analytics_search_details",
        domain="analytics",
        description="Get search query details",
        params_model=AnalyticsSearchDetailsParams,
        api_method="get_analytics_search_details",
        keywords=["analytics", "search", "details"],
    ),
    Action(
        id="wb_analytics_search_texts",
        domain="analytics",
        description="Get search phrases for product",
        params_model=AnalyticsSearchTextsParams,
        api_method="get_analytics_search_texts",
        keywords=["analytics", "search", "texts"],
    ),
    Action(
        id="wb_analytics_search_orders",
        domain="analytics",
        description="Get orders by search phrase",
        params_model=AnalyticsSearchOrdersParams,
        api_method="get_analytics_search_orders",
        keywords=["analytics", "search", "orders"],
    ),
    Action(
        id="wb_analytics_stocks_wb",
        domain="analytics",
        description="Get WB warehouse stock data",
        params_model=AnalyticsStocksWbParams,
        api_method="get_analytics_stocks_wb",
        keywords=["analytics", "stocks", "wb"],
    ),
    Action(
        id="wb_analytics_stocks_groups",
        domain="analytics",
        description="Get grouped inventory data",
        params_model=AnalyticsStocksGroupsParams,
        api_method="get_analytics_stocks_products_groups",
        keywords=["analytics", "stocks", "groups"],
    ),
    Action(
        id="wb_analytics_stocks_products",
        domain="analytics",
        description="Get product inventory data",
        params_model=AnalyticsStocksProductsParams,
        api_method="get_analytics_stocks_products",
        keywords=["analytics", "stocks", "products"],
    ),
    Action(
        id="wb_analytics_stocks_sizes",
        domain="analytics",
        description="Get inventory by size",
        params_model=AnalyticsStocksSizesParams,
        api_method="get_analytics_stocks_sizes",
        keywords=["analytics", "stocks", "sizes"],
    ),
    Action(
        id="wb_analytics_stocks_offices",
        domain="analytics",
        description="Get warehouse inventory data",
        params_model=AnalyticsStocksOfficesParams,
        api_method="get_analytics_stocks_offices",
        keywords=["analytics", "stocks", "offices"],
    ),
    Action(
        id="wb_analytics_csv_create",
        domain="analytics",
        description="Create analytics CSV report",
        params_model=AnalyticsCsvCreateParams,
        api_method="create_analytics_csv_report",
        keywords=["analytics", "csv", "create"],
    ),
    Action(
        id="wb_analytics_csv_list",
        domain="analytics",
        description="Get list of analytics CSV reports",
        params_model=None,
        api_method="get_analytics_csv_reports",
        keywords=["analytics", "csv", "list"],
    ),
    Action(
        id="wb_analytics_csv_retry",
        domain="analytics",
        description="Retry CSV report generation",
        params_model=AnalyticsCsvRetryParams,
        api_method="retry_analytics_csv_report",
        keywords=["analytics", "csv", "retry"],
    ),
    Action(
        id="wb_analytics_csv_download",
        domain="analytics",
        description="Download analytics CSV report",
        params_model=DownloadIdParams,
        api_method="download_analytics_csv_report",
        is_file=True,
        keywords=["analytics", "csv", "download"],
    ),

    # ======================================================================
    # Domain: reports  (24 actions)
    # ======================================================================
    Action(
        id="wb_report_orders",
        domain="reports",
        description="Get orders report",
        params_model=ReportOrdersParams,
        api_method="get_report_orders",
        keywords=["report", "orders", "заказы"],
    ),
    Action(
        id="wb_report_sales",
        domain="reports",
        description="Get sales report",
        params_model=ReportOrdersParams,
        api_method="get_report_sales",
        keywords=["report", "sales", "продажи"],
    ),
    Action(
        id="wb_report_warehouse_remains_create",
        domain="reports",
        description="Create warehouse remains report task",
        params_model=None,
        api_method="create_report_warehouse_remains",
        keywords=["report", "warehouse", "remains", "create"],
    ),
    Action(
        id="wb_report_warehouse_remains_status",
        domain="reports",
        description="Check warehouse remains report status",
        params_model=TaskIdParams,
        api_method="get_report_warehouse_remains_status",
        keywords=["report", "warehouse", "remains", "status"],
    ),
    Action(
        id="wb_report_warehouse_remains_download",
        domain="reports",
        description="Download warehouse remains report",
        params_model=TaskIdParams,
        api_method="download_report_warehouse_remains",
        is_file=True,
        keywords=["report", "warehouse", "remains", "download"],
    ),
    Action(
        id="wb_report_excise",
        domain="reports",
        description="Get excise/marking report",
        params_model=ReportExciseParams,
        api_method="get_report_excise",
        keywords=["report", "excise", "маркировка"],
    ),
    Action(
        id="wb_report_measurement_penalties",
        domain="reports",
        description="Get dimension measurement deductions",
        params_model=None,
        api_method="get_report_measurement_penalties",
        keywords=["report", "measurement"],
    ),
    Action(
        id="wb_report_warehouse_measurements",
        domain="reports",
        description="Get warehouse measurement data",
        params_model=None,
        api_method="get_report_warehouse_measurements",
        keywords=["report", "warehouse", "measurements"],
    ),
    Action(
        id="wb_report_deductions",
        domain="reports",
        description="Get substitution deductions",
        params_model=None,
        api_method="get_report_deductions",
        keywords=["report", "deductions", "удержания"],
    ),
    Action(
        id="wb_report_antifraud",
        domain="reports",
        description="Get self-purchase deductions",
        params_model=None,
        api_method="get_report_antifraud",
        keywords=["report", "antifraud", "самовыкуп"],
    ),
    Action(
        id="wb_report_labeling",
        domain="reports",
        description="Get marking penalties",
        params_model=None,
        api_method="get_report_labeling",
        keywords=["report", "labeling", "маркировка"],
    ),
    Action(
        id="wb_report_acceptance_create",
        domain="reports",
        description="Create acceptance report task",
        params_model=None,
        api_method="create_report_acceptance",
        keywords=["report", "acceptance", "create"],
    ),
    Action(
        id="wb_report_acceptance_status",
        domain="reports",
        description="Check acceptance report status",
        params_model=TaskIdParams,
        api_method="get_report_acceptance_status",
        keywords=["report", "acceptance", "status"],
    ),
    Action(
        id="wb_report_acceptance_download",
        domain="reports",
        description="Download acceptance report",
        params_model=TaskIdParams,
        api_method="download_report_acceptance",
        is_file=True,
        keywords=["report", "acceptance", "download"],
    ),
    Action(
        id="wb_report_paid_storage_create",
        domain="reports",
        description="Create paid storage report task",
        params_model=None,
        api_method="create_report_paid_storage",
        keywords=["report", "storage", "create"],
    ),
    Action(
        id="wb_report_paid_storage_status",
        domain="reports",
        description="Check paid storage report status",
        params_model=TaskIdParams,
        api_method="get_report_paid_storage_status",
        keywords=["report", "storage", "status"],
    ),
    Action(
        id="wb_report_paid_storage_download",
        domain="reports",
        description="Download paid storage report",
        params_model=TaskIdParams,
        api_method="download_report_paid_storage",
        is_file=True,
        keywords=["report", "storage", "download"],
    ),
    Action(
        id="wb_report_regional_sales",
        domain="reports",
        description="Get regional sales report",
        params_model=None,
        api_method="get_report_regional_sales",
        keywords=["report", "regional", "sales"],
    ),
    Action(
        id="wb_report_brands",
        domain="reports",
        description="Get seller brands",
        params_model=None,
        api_method="get_report_brands",
        keywords=["report", "brands"],
    ),
    Action(
        id="wb_report_brand_categories",
        domain="reports",
        description="Get brand categories",
        params_model=None,
        api_method="get_report_brand_categories",
        keywords=["report", "brand", "categories"],
    ),
    Action(
        id="wb_report_brand_share",
        domain="reports",
        description="Get brand share report",
        params_model=ReportBrandShareParams,
        api_method="get_report_brand_share",
        keywords=["report", "brand", "share"],
    ),
    Action(
        id="wb_report_blocked_products",
        domain="reports",
        description="Get blocked products",
        params_model=None,
        api_method="get_report_blocked_products",
        keywords=["report", "blocked"],
    ),
    Action(
        id="wb_report_shadowed_products",
        domain="reports",
        description="Get shadowed products",
        params_model=None,
        api_method="get_report_shadowed_products",
        keywords=["report", "shadowed"],
    ),
    Action(
        id="wb_report_returns",
        domain="reports",
        description="Get returns report",
        params_model=None,
        api_method="get_report_returns",
        keywords=["report", "returns", "возвраты"],
    ),

    # ======================================================================
    # Domain: finance  (12 actions)
    # ======================================================================
    Action(
        id="wb_finance_balance",
        domain="finance",
        description="Get seller account balance",
        params_model=None,
        api_method="get_finance_balance",
        keywords=["finance", "balance", "баланс"],
    ),
    Action(
        id="wb_finance_sales_reports",
        domain="finance",
        description="Get sales reports list",
        params_model=FinanceSalesReportsListParams,
        api_method="get_finance_sales_reports",
        keywords=["finance", "sales", "reports"],
    ),
    Action(
        id="wb_finance_sales_report_detail",
        domain="finance",
        description="Get detailed sales report",
        params_model=ReportIdParams,
        api_method="get_finance_sales_report_detail",
        keywords=["finance", "sales", "detail"],
    ),
    Action(
        id="wb_finance_sales_report_by_period",
        domain="finance",
        description="Get sales report for period",
        params_model=FinanceSalesReportByPeriodParams,
        api_method="get_finance_sales_report_by_period",
        keywords=["finance", "sales", "period"],
    ),
    Action(
        id="wb_finance_report_detail_by_period",
        domain="finance",
        description="Get realization report",
        params_model=FinanceReportDetailParams,
        api_method="get_finance_report_detail_by_period",
        keywords=["finance", "report", "realization"],
    ),
    Action(
        id="wb_finance_acquiring_reports",
        domain="finance",
        description="Get acquiring reports",
        params_model=FinanceAcquiringReportsListParams,
        api_method="get_finance_acquiring_reports",
        keywords=["finance", "acquiring"],
    ),
    Action(
        id="wb_finance_acquiring_detail",
        domain="finance",
        description="Get detailed acquiring report",
        params_model=ReportIdParams,
        api_method="get_finance_acquiring_detail",
        keywords=["finance", "acquiring", "detail"],
    ),
    Action(
        id="wb_finance_acquiring_by_period",
        domain="finance",
        description="Get acquiring for period",
        params_model=FinanceAcquiringByPeriodParams,
        api_method="get_finance_acquiring_by_period",
        keywords=["finance", "acquiring", "period"],
    ),
    Action(
        id="wb_finance_document_categories",
        domain="finance",
        description="Get document categories",
        params_model=None,
        api_method="get_finance_document_categories",
        keywords=["finance", "documents", "categories"],
    ),
    Action(
        id="wb_finance_documents",
        domain="finance",
        description="Get seller documents list",
        params_model=FinanceDocumentsListParams,
        api_method="get_finance_documents",
        keywords=["finance", "documents"],
    ),
    Action(
        id="wb_finance_document_download",
        domain="finance",
        description="Download document",
        params_model=DocIdParams,
        api_method="download_finance_document",
        is_file=True,
        keywords=["finance", "document", "download"],
    ),
    Action(
        id="wb_finance_documents_download",
        domain="finance",
        description="Download multiple documents",
        params_model=DocIdsParams,
        api_method="download_finance_documents",
        is_file=True,
        keywords=["finance", "documents", "download"],
    ),

    # ======================================================================
    # Domain: wbd  (12 actions)
    # ======================================================================
    Action(
        id="wb_wbd_keys_add",
        domain="wbd",
        description="Add activation keys",
        params_model=WbdKeysParams,
        api_method="add_wbd_keys",
        keywords=["wbd", "keys", "add"],
    ),
    Action(
        id="wb_wbd_keys_delete",
        domain="wbd",
        description="Delete activation keys",
        params_model=WbdKeysParams,
        api_method="delete_wbd_keys",
        is_destructive=True,
        keywords=["wbd", "keys", "delete"],
    ),
    Action(
        id="wb_wbd_keys_redeemed",
        domain="wbd",
        description="Get redeemed keys",
        params_model=WbdOfferIdParams,
        api_method="get_wbd_redeemed_keys",
        keywords=["wbd", "keys", "redeemed"],
    ),
    Action(
        id="wb_wbd_keys_count",
        domain="wbd",
        description="Get key count",
        params_model=WbdOfferIdParams,
        api_method="get_wbd_keys_count",
        keywords=["wbd", "keys", "count"],
    ),
    Action(
        id="wb_wbd_keys_list",
        domain="wbd",
        description="Get keys list",
        params_model=WbdOfferIdParams,
        api_method="get_wbd_keys_list",
        keywords=["wbd", "keys", "list"],
    ),
    Action(
        id="wb_wbd_offer_create",
        domain="wbd",
        description="Create digital offer",
        params_model=PassThroughParams,
        api_method="create_wbd_offer",
        keywords=["wbd", "offer", "create"],
    ),
    Action(
        id="wb_wbd_offer_update",
        domain="wbd",
        description="Update digital offer",
        params_model=WbdOfferUpdateParams,
        api_method="update_wbd_offer",
        keywords=["wbd", "offer", "update"],
    ),
    Action(
        id="wb_wbd_offer",
        domain="wbd",
        description="Get digital offer info",
        params_model=WbdOfferIdParams,
        api_method="get_wbd_offer",
        keywords=["wbd", "offer"],
    ),
    Action(
        id="wb_wbd_offers",
        domain="wbd",
        description="Get digital offers list",
        params_model=None,
        api_method="get_wbd_offers",
        keywords=["wbd", "offers"],
    ),
    Action(
        id="wb_wbd_offer_price",
        domain="wbd",
        description="Update digital offer price",
        params_model=WbdOfferPriceParams,
        api_method="update_wbd_offer_price",
        keywords=["wbd", "offer", "price"],
    ),
    Action(
        id="wb_wbd_offer_status",
        domain="wbd",
        description="Update digital offer status",
        params_model=WbdOfferStatusParams,
        api_method="update_wbd_offer_status",
        keywords=["wbd", "offer", "status"],
    ),
    Action(
        id="wb_wbd_catalog",
        domain="wbd",
        description="Get WBD catalog",
        params_model=None,
        api_method="get_wbd_catalog",
        keywords=["wbd", "catalog"],
    ),
]

# ---------------------------------------------------------------------------
# Quick-lookup dict by action ID
# ---------------------------------------------------------------------------

ACTIONS: dict[str, Action] = {a.id: a for a in _ACTIONS_LIST}
